os:
    - linux
    - osx

dist: xenial

addons:
    apt:
        packages:
            - qemu

language: rust
rust:
    - nightly

script:
    - rustup component add rust-src clippy
    - cargo install bootimage cargo-xbuild
    - cargo xcheck
    - cargo xclippy
    - cargo xbuild
    - cargo xtest

cache:
    timeout: 1000
    directories:
        - /nix/store

branches:
    only:
        - master

notifications:
    email:
        on_success: never
