os:
    - linux

dist: xenial

addons:
    apt:
        packages:
            - qemu

language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

script:
    #- nix-shell --run 'make test'
    - cargo install bootimage cargo-xbuild
    - cargo xcheck
    - cargo xclippy
    - carbo xbuild

cache:
    timeout: 1000
    directories:
        - /nix/store

branches:
    only:
        - master

notifications:
    email:
        on_success: never
