os:
  - linux

dist: xenial

addons:
    apt:
        packages:
            - qemu
git:
    submodules: false

language: nix

script:
    - nix-shell --run 'make test'

cache:
    timeout: 10000
    directories:
        - /nix/store

branches:
    only:
        - master

notifications:
    email:
        on_success: never
