os:
  - linux

dist: xenial

addons:
    apt:
        packages:
            - qemu

language: nix
nix: 2.1.3

script:
    #- nix-shell --run 'make test'
    - cargo install bootimage cargo-xbuild
    - cargo xcheck
    - cargo xclippy
    - carbo xbuild

cache:
    timeout: 1000
    directories:
        - /nix/store

branches:
    only:
        - master

notifications:
    email:
        on_success: never
