[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.5"
multiboot2 = "0.3.2"
bitflags = "0.9.1"
x86_64 = "0.1.2"