[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[package.metadata.bootimage]
default-target = "x86_64-daedalos.json"

[dependencies]
array-init = "0.0.4"
bootloader = "0.3.14"
pic8259_simple = "0.1.1"
spin = "0.5.0"
uart_16550 = "0.1.0"
volatile = "0.2.6"
x86_64 = "0.4.2"

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[features]
integration-test = []

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"
