[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.12"
spin = "0.5.0"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.2.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
default-target = "x86_64-daedalos.json"

[profile.dev]
opt-level = 2
lto = false
debug = true
codegen-units = 4
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"
