[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[dependencies]
array-init = "0.0.4"
bootloader = "0.3.12"
spin = "0.5.0"
uart_16550 = "0.1.0"
volatile = "0.2.6"
x86_64 = "0.4.0"

[dependencies.lazy_static]
version = "1.2.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
default-target = "x86_64-daedalos.json"

[features]
integration-test = []

[profile.dev]
opt-level = 2
lto = false
debug = true
codegen-units = 4
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"
