[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 2
lto = false
debug = true
codegen-units = 4
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"
