[package]
name = "daedalos"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 2
debug = true
lto = false
codegen-units = 4
panic = "abort"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
panic = "abort"
